//
// Created by gjk on 12/11/19.
//

#ifndef KYHTTPSERVER_HTTPSTATE_H
#define KYHTTPSERVER_HTTPSTATE_H
enum HTTP_REQUEST_METHOD{
    METHOD_HEAD,
    METHOD_GET,
    METHOD_POST
};
enum HTTP_VERSION{
    HTTP_1_0,
    HTTP_1_1
};


#endif //KYHTTPSERVER_HTTPSTATE_H
